spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/data_jpa
    username: gabriel
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
